[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"
authors = ["Bin Wang <wkk@user.noreply.github.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.5"
itertools = "0.10.3"
scan_fmt = "0.2.6"
